### ISSUE TITLE
Java Index error when processing single ticket (1.3.2)

### ISSUE THREAD

**Issue by cornesto** [QIntegration/Qualys-Jira-Connector#11]
I've gotten stuck troubleshooting the following java error on a new deployment setup. At the moment we should only be generating a single detection for testing purposes as we don't want to flood our Jira board with tickets just yet until we sort out our new workflow. This is the error in the Jira log file.

```
2024-12-05 16:50:26,661 [ForkJoinPool-1-worker-1] INFO  c.q.j.task.ProcessOutputFileTask                   - [VMDR] Reading output file - hd_C901B9485ACE2D4291BAD0E296C68484364B8A3B67A2BDD1001F9A918D4CC114_0_1.json
2024-12-05 16:50:26,764 [ForkJoinPool-1-worker-1] INFO  profileLogger                                      - [VMDR] Processing single tickets
2024-12-05 16:50:26,767 [ForkJoinPool-1-worker-1] INFO  profileLogger                                      - [VMDR] Ticket data picked up for primary key - HostID:299957650-QID:43051-Port: and issue type - Host Vulnerability
2024-12-05 16:50:26,767 [ForkJoinPool-1-worker-1] INFO  profileLogger                                      - [VMDR] Checking if ticket already exists
2024-12-05 16:50:26,776 [ForkJoinPool-1-worker-1] ERROR profileLogger                                      - [VMDR] An error occurred while processing detection data. Error: Index 1 out of bounds for length 1java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at com.qualys.jiraclient.Ticketing.convertCFToJQLFormat(Ticketing.java:193)
        at com.qualys.jiraclient.Ticketing.ticketExists(Ticketing.java:108)
        at com.qualys.jiraclient.Ticketing.createOrUpdateTicket(Ticketing.java:558)
        at com.qualys.jiraclient.Ticketing.processSingleTicketData(Ticketing.java:431)
        at com.qualys.jiraclient.Ticketing.processData(Ticketing.java:369)
        at com.qualys.jiraclient.task.ProcessOutputFileTask.readOutputFile(ProcessOutputFileTask.java:118)
        at com.qualys.jiraclient.task.ProcessOutputFileTask.processOutputFile(ProcessOutputFileTask.java:60)
        at com.qualys.jiraclient.service.JiraClientService.submitFilesForProcessing(JiraClientService.java:128)
        at com.qualys.jiraclient.service.JiraClientService.lambda$submitFilesForEachModule$2(JiraClientService.java:109)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1375)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

Note that this particular detection does not involve a specific port, therefor the port number is blank... not sure if that's what's causing the error or some bug in the way single tickets are being handled where the array index value is getting extended beyond 0?

**Comment by simonshtipelman** [comment]
Hey, not sure if you still have this problem, but I had the same issue and Qualys Support helped me out. Turned out the way I referenced the customfield id's in the templates was causing the problem. 

It is supposed to be
"customFieldId": "customfield_XXXX"
not
"customFieldId": "XXXX"
